[package]
authors = ["darrentsung"]
edition = "2018"
name = "rkyv-clippy-repro"
version = "0.1.0"

[dependencies]
rkyv = {version = "0.7.33", features = ["uuid"]}
uuid = {version = "0.8", features = ["v4"]}
